[project]
name = "gauth-python"
version = "0.0.1"
authors = [
  { name="Noh Gaseong", email="dev.yohan05@gmail.com" },
]
description = "Python sdk from Gauth."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/GSM-MSG/GAuth-SDK-Python"
"Bug Tracker" = "https://github.com/GSM-MSG/GAuth-SDK-Python/issues"